- name: 01 patch LuaJIT to embed rds.parser
  lineinfile:
    path: "{{ openresty_version_build_path }}/bundle/{{ _luajit_dir.stdout }}/src/lib_init.c"
    insertafter: '#include "lj_arch.h"'
    line: |

      LUALIB_API int luaopen_rds_parser(lua_State *l);

- name: 02 patch LuaJIT to embed rds.parser
  lineinfile:
    path: "{{ openresty_version_build_path }}/bundle/{{ _luajit_dir.stdout }}/src/lib_init.c"
    insertafter: 'static const luaL_Reg lj_lib_preload'
    line: |-
      { "rds.parser",		luaopen_rds_parser },

- name: register rds-parser directory name
  shell: "echo lua-rds-parser-*"
  register: _rds_parser_dir
  args:
    chdir: "{{ openresty_version_build_path }}/bundle/"

- name: build rds_parser.o
  command: >
    make src/rds_parser.o
  environment:
    LUA_INCLUDE_DIR: "{{ openresty_version_build_path }}/bundle/{{ _luajit_dir.stdout }}/src"
  args:
    chdir: "{{ openresty_version_build_path }}/bundle/{{ _rds_parser_dir.stdout }}"

- name: create librdsparser.a
  command: >
    ar rcus {{ openresty_build_path }}/librdsparser.a src/rds_parser.o
  args:
    chdir: "{{ openresty_version_build_path }}/bundle/{{ _rds_parser_dir.stdout }}"

- name: add rdsparser to TARGET_LIBS
  set_fact:
    _luajit_target_libs: "{{ _luajit_target_libs|default('') }} -L{{ openresty_build_path }} -lrdsparser"
    _ngx_ld_opt: "{{ _ngx_ld_opt|default('') }} -lrdsparser"
